version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: local-Admin-situs-forum
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=situsForum
      - MYSQL_DATABASE=SitusForum
    networks:
      - my_network

networks:
  my_network:
    driver: bridge